spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      stat-view-servlet:
        # 启用
        enabled: true
        # 用户名和密码
        login-password: admin
        login-username: admin
      #        url-pattern: "/druid/"
      # 连接池配置
      initial-size: 5
      max-active: 40
      max-wait: 60000
      min-idle: 3
      username: postgres
      password: 296003
    url: jdbc:postgresql://localhost:5432/test?useSSL=false&characterEncoding=utf8
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
logging:
  level:
    web: DEBUG
    org:
      springframework: INFO
    cn.yunqiaold: DEBUG

jwt:
  # 过期时间 单位是秒
  expiration: 86400
  secret: 851357f5b2fcc5e3b94112e7fd59747ce406beb618cafe3e6b22b10009a6448a

